name: Docker Build/Publish Preview Image from branch
on:
  push:
    branches-ignore:
    - main
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Define revision
      id: revision
      run: |
        echo "target-revision=preview-${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Docker login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Docker build/push
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm/v7,linux/arm64
        tags: |
          "sfudeus/rctmon:${{ steps.revision.outputs.target-revision }}"
        push: true
